CREATE DATABASE DML;
USE DML;

CREATE TABLE CLIENTE(
	COD_CLIENTE INT NOT NULL,
    NOME VARCHAR(50),
    CPF VARCHAR(14),
    RUA VARCHAR(50),
    NUM VARCHAR(5),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    UF VARCHAR(2),
    CEP VARCHAR(9),
    PRIMARY KEY(COD_CLIENTE)
);

INSERT INTO CLIENTE (COD_CLIENTE, NOME, CPF, RUA, NUM, BAIRRO, CIDADE, UF, CEP) VALUES (1, 'GILBERTO', '12345678901', 'AV. Astronautas', '1333', 'Cidade Jardim', 'S. J. Dos Campos', 'SP', '12227-220');

#ERRADO
#	ESTA ERRADO POIS O COD_CLIENTE ESTA IGUAL AO INDICE ANTERIOR
#	INSERT INTO CLIENTE (COD_CLIENTE, NOME, CPF, RUA, NUM, BAIRRO, CIDADE, UF, CEP) VALUES (1, 'EDUARDO', '12345678902', 'AV. X', '1456', 'Vila', 'Rio de Janeiro', 'RJ', '35000000');

#CORRETO
INSERT INTO CLIENTE (COD_CLIENTE, NOME, CPF, RUA, NUM, BAIRRO, CIDADE, UF, CEP) VALUES (2, 'EDUARDO', '12345678902', 'AV. X', '1456', 'Vila', 'Rio de Janeiro', 'RJ', '35000-000');


#ERRADO
#NESTE CASO TUDO ESTA ERRADO PRIMEIRO POR CONTA DA ORDEM DOS INDICES E POSTERIORMENTE NÃO É TOTALMENTE ERRADO MAS A FALTA DAS INFORMAÇÕES AO LONGO PRAZO PODE SER PROBLEMATICO
#	INSERT INTO CLIENTE VALUES (2, 'BRUNO', '12345678902', 'RUA ALBINO SARTORI', '95', 'V. S. J.', 'OURO PRETO', 'MG', '35400-000');
#	INSERT INTO CLIENTE VALUES (3, 'RICARDO', '12345678903', 'RUA CECI');
#	INSERT INTO CLIENTE VALUES ('ANTONIO', '12345678904');

#CORRETO
INSERT INTO CLIENTE VALUES (3, 'BRUNO', '12345678902', 'RUA ALBINO SARTORI', '95', 'V. S. J.', 'OURO PRETO', 'MG', '35400-000');

INSERT INTO CLIENTE VALUES (4, 'RICARDO', '12345678903', 'RUA CECI', '195', 'SLA.', 'OQ', 'AC', '35400-001');

INSERT INTO CLIENTE VALUES (5, 'ANTONIO', '12345678904', 'RUA CECILIA', '295', 'VILA SÃO JOJÓ', 'PINDAMONHANGABA', 'SP', '35400-002');

#ERRADO
#AQUI ESTA ERRADO OS PARAMETROS.
#	DELETE FROM CLIENTE WHERE COD_CLIENTE<0;
#	DELETE FROM CLIENTE WHERE NOME='bruno';
#	DELETE FROM CLIENTE;

#CORRETO
DELETE FROM CLIENTE WHERE COD_CLIENTE<3;
DELETE FROM CLIENTE WHERE NOME='BRUNO';
DELETE FROM CLIENTE WHERE CPF='12345678904';

#ERRADO
#A PRIMEIRA ESTA ERRADO NOVAMENTE POR CAUSA DOS PARAMETROS
#	UPDATE CLIENTE SET NOME='JOÃO' WHERE COD_CLIENTE=0;
#	UPDATE CLIENTE SET NOME='JOÃO' WHERE NOME='BRUNO';

#CORRETO
UPDATE CLIENTE SET NOME='JOÃO' WHERE COD_CLIENTE=1;
UPDATE CLIENTE SET NOME='JOÃO' WHERE NOME='BRUNO';















