CREATE DATABASE EXERC;
USE EXERC;

CREATE TABLE CLIENTE(
	ID_C INT auto_increment,
	NOME VARCHAR(50),
    IDADE INT,
    CNH VARCHAR(50),
    METODO_PAG VARCHAR(50),
    PRIMARY KEY (ID_C)
);

CREATE TABLE VEICULOS(
	ID_V INT auto_increment,
	NOME VARCHAR(50),
    PLACA VARCHAR(50),
    MODELO VARCHAR(50),
    COR VARCHAR(50),
    PRIMARY KEY (ID_V)
);

INSERT INTO CLIENTE VALUES ("", "JORGE", "18", "01293012930", "CARTÃO"); 
INSERT INTO CLIENTE VALUES ("", "JORGE1", "22", "01293012932", "DINHEIRO");
INSERT INTO CLIENTE VALUES ("", "JORGE2", "26", "01293012934", "CARTÃO");
INSERT INTO CLIENTE VALUES ("", "JORGE3", "30", "01293012936", "DINHEIRO");

INSERT INTO VEICULOS VALUES ("CORSA", "EIW8975", "AIWHDIWAHDA-087", "VERMELHO");
INSERT INTO VEICULOS VALUES ("CELTA", "EIW8975", "AIWHDIWAHDA-087", "VERMELHO");
INSERT INTO VEICULOS VALUES ("RANGER", "EIW8975", "AIWHDIWAHDA-087", "VERMELHO");
INSERT INTO VEICULOS VALUES ("UNO", "EIW8975", "AIWHDIWAHDA-087", "VERMELHO");

#INNER
SELECT a.NOME, b.NOME
FROM CLIENTE as a
INNER JOIN VEICULOS as b
					on a.NOME = b.NOME;

#LEFT
SELECT a.NOME, b.NOME
FROM CLIENTE as a
LEFT JOIN VEICULOS as b
					on a.NOME = b.NOME;
                    
#RIGHT
SELECT a.NOME, b.NOME
FROM CLIENTE as a
RIGHT JOIN VEICULOS as b
					on a.NOME = b.NOME;  
                    
#OUTER
SELECT *
FROM CLIENTE as a
LEFT JOIN VEICULOS as b 
					on a.NOME = b.NOME
WHERE b.NOME is NULL

UNION   

SELECT *
FROM CLIENTE as a
right JOIN VEICULOS as b on a.NOME = B.NOME
WHERE a.NOME IS NULL;     

#FULL
SELECT a.NOME, b.NOME
FROM CLIENTE as a
LEFT JOIN VEICULOS as b 
					on a.NOME = b.NOME

UNION   

SELECT a.NOME, b.NOME
FROM CLIENTE as a
right JOIN VEICULOS as b 
					on a.NOME = B.NOME;     
                    
#LEFT OUTER
SELECT a.NOME, b.NOME
FROM CLIENTE as a
LEFT JOIN VEICULOS as b
					on a.NOME = b.NOME
WHERE b.NOME IS NULL;        

CREATE VIEW cliente_passagem AS

	SELECT nome, passagem.num, poltrona
    FROM CLIENTE, VEICULOS
    WHERE cliente.cod_cli = passagem.cod_cli
		ORDER BY nome, num;
     
SELECT * FROM cliente_passagem;

DROP VIEW cliente_passagem; 