CREATE DATABASE FABRICA_ROUPAS;
USE FABRICA_ROUPAS;

CREATE TABLE SETOR(
	`ID_SETOR` INT NOT NULL,
    `DESCRICAO` VARCHAR(200),
    PRIMARY KEY (`ID_SETOR`)
);

CREATE TABLE FUNCIONARIO(
	`ID_FUNCIONARIO` INT NOT NULL,
	`FUNCAO` VARCHAR(200),
    `NOME` VARCHAR(200),
    `GENERO` VARCHAR(200),
    `DATA_NASC` date,
    `FK_SETOR` INT,
    PRIMARY KEY (`ID_FUNCIONARIO`),
    FOREIGN KEY (`FK_SETOR`) REFERENCES SETOR (`ID_SETOR`)
);

CREATE TABLE PAGAMENTO(
	`ID_PAGAMENTO` INT NOT NULL,
    `DATA` DATE,
    `VALOR` FLOAT,
    `BANCO` VARCHAR(200),
    `NUMERO_CONTA` INT NOT NULL,
    `AGENCIA` VARCHAR(200),
    `FK_FUNCIONARIO` INT,
    PRIMARY KEY (`ID_PAGAMENTO`),
    FOREIGN KEY (`FK_FUNCIONARIO`) REFERENCES FUNCIONARIO (`ID_FUNCIONARIO`)
);

CREATE TABLE ROUPA(
	`ID_ROUPA` INT NOT NULL,
    `DESCRICAO` VARCHAR(200),
    `PRECO` FLOAT,
    PRIMARY KEY (`ID_ROUPA`)
);

CREATE TABLE ITEM_PAGAMENTO(
	`FK_PAGAMENTO` INT,
    `FK_ROUPA` INT,
    `VALOR_TOTAL` FLOAT,
    `COMISSAO` FLOAT,
    FOREIGN KEY (`FK_PAGAMENTO`) REFERENCES PAGAMENTO (`ID_PAGAMENTO`),
    FOREIGN KEY (`FK_ROUPA`) REFERENCES ROUPA (`ID_ROUPA`)
);

CREATE TABLE MAQUINARIO(
	`ID_MAQUINA` INT NOT NULL,
    `TIPO` VARCHAR(200),
    `STATUS` VARCHAR(200),
    `DATA` DATE,
    `ID_TIPO_MAQUINA` INT,
    PRIMARY KEY (`ID_MAQUINA`)
);

CREATE TABLE PRODUCAO(
	`ID_FUNCIONARIO_COSTUREIRA` INT,
    `ID_FUNCIONARIO_SUPERVISORA` INT,
    `FK_MAQUINA` INT,
    `FK_ROUPA` INT,
    `DATA_HORA` DATETIME,
    `STATUS` VARCHAR(200),
    FOREIGN KEY (`FK_MAQUINA`) REFERENCES MAQUINARIO (`ID_MAQUINA`),
    FOREIGN KEY (`FK_ROUPA`) REFERENCES ROUPA (`ID_ROUPA`)
); 

CREATE TABLE TIPO_COSTURA(
	`ID_TIPO_COSTURA` INT NOT NULL,
    `TIPO` VARCHAR(200),
    `TIPO_AGULHA` VARCHAR(200),
    `TIPO_LINHA` VARCHAR(200),
    PRIMARY KEY (`ID_TIPO_COSTURA`)
);